def print_art():
	print("                                                          .;;,")
	print("                                     .,.               .,;;;;;,")
	print("                                    ;;;;;;;,,        ,;;%%%%%;;")
	print("                                     `;;;%%%%;;,.  ,;;%%;;%%%;;")
	print("                                       `;%%;;%%%;;,;;%%%%%%%;;'")
	print("                                         `;;%%;;%:,;%%%%%;;%%;;,")
	print("                                            `;;%%%,;%%%%%%%%%;;;")
	print("                                               `;:%%%%%%;;%%;;;'")
	print("           ..,,,.                                 .:::::::.")
	print("        .;;;;;;;;;;,.                                  s.")
	print("        `;;;;;;;;;;;;;,                               ,SSSs.")
	print("          `:.:.:.:.:.:.:.                            ,SSSSSSs.")
	print("           .;;;;;;;;;;;;;::,                        ,SSSSSSSSS,")
	print("          ;;;;;;;;;;;;;;;;:::%,                    ,SS%;SSSSSSsS")
	print("         ;;;;;;,:,:::::::;::::%%,                  SS%;SSSSSSsSS")
	print("         ;;;;;,::a@@@@@@a::%%%%%%%,.   ...         SS%;SSSSSSSS'")
	print("         `::::::@@@@@@@@@@@a;%%%%%%%%%'  \#;        `SS%;SSSSS'")
	print("  .,sSSSSs;%%,::@@@@@@;;' \#`@@a;%%%%%'   ,'          `S%;SS'")
	print("sSSSSSSSSSs;%%%,:@@@@a;;   .@@@a;%%sSSSS'           .%%%;SS,")
	print("`SSSSSSSSSSSs;%%%,:@@@a;;;;@@@;%%sSSSS'        ..,,%%%;SSSSSSs.")
	print("  `SSSSSSSSSSSSs;%%,%%%%%%%%%%%SSSS'     ..,,%;sSSS;%;SSSSSSSSs.")
	print("     `SSSSSSSSSSS%;%;sSSSS;\"\"\"\"   ..,,%sSSSS;;SSSS%%%;SSSSSSSSSS.")
	print("         \"\"\"\"\"\" %%;SSSSSS;;%..,,sSSS;%SSSSS;%;%%%;%%%%;SSSSSS;SSS.")
	print("                `;SSSSS;;%%%%%;SSSS;%%;%;%;sSSS;%%%%%%%;SSSSSS;SSS")
	print("                 ;SSS;;%%%%%%%%;%;%sSSSS%;SSS;%%%%%%%%%;SSSSSS;SSS")
	print("                 `S;;%%%%%%%%%%%%%SSSSS;%%%;%%%%%%%%%%%;SSSSSS;SSS")
	print("                 `S;;%%%%%%%%%%%%%SSSSS;%%%;%%%%%%%%%%%;SSSSSS;SSS")
	print("                  ;SS;%%%%%%%%%%%%;%;%;%%;%%%%%%%%%%%%;SSSSSS;SSS'")
	print("                  SS;%%%%%%%%%%%%%%%%%%%;%%%%%%%%%%%;SSSSSS;SSS'")
	print("                  SS;%%%%%%%%%%%%%%%%%%;%%%%%%%%%%%;SSSSS;SSS'")
	print("                  SS;%%%%%%%%%%%%%;sSSs;%%%%%%%%;SSSSSS;SSSS")
	print("                  `SS;%%%%%%%%%%%%%%;SS;%%%%%%;SSSSSS;SSSS'")
	print("                   `S;%%%%%%%%%%%%%%%;S;%%%%%;SSSS;SSSSS%")
	print("                    `S;%;%%%%%%%%%%%'   `%%%%;SSS;SSSSSS%.")
	print("                  ,S;%%%%%%%%%%;'      `%%%%%;S   `SSSSs%,.")
	print("                  ,%%%%%%%%%%;%;'         `%;%%%;     `SSSs;%%,.")
	print("               ,%%%%%%;;;%;;%;'           .%%;%%%       `SSSSs;%%.")
	print("            ,%%%%%' .%;%;%;'             ,%%;%%%'         `SSSS;%%")
	print("          ,%%%%'   .%%%%'              ,%%%%%'             `SSs%%'")
	print("        ,%%%%'    .%%%'              ,%%%%'                ,%%%'")
	print("      ,%%%%'     .%%%              ,%%%%'                 ,%%%'")
	print("    ,%%%%'      .%%%'            ,%%%%'                  ,%%%'")
	print("  ,%%%%'        %%%%           ,%%%'                    ,%%%%")
	print("  %%%%'       .:::::         ,%%%'                      %%%%'")
	print(".:::::        :::::'       ,%%%'                       ,%%%%")
	print(":::::'                   ,%%%%'                        %%%%%")
	print("                        %%%%%'                         %%%%%")
	print("                      .::::::                        .::::::")
	print("                      ::::::'                        ::::::::")
